//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Supplier
    {
        public Book_Supplier()
        {
            this.Prospective_Book = new HashSet<Prospective_Book>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int BookSupplier_ID { get; set; }
        public string BookSupplier_Name { get; set; }
        public string BookSupplier_Surname { get; set; }
        public string BookSupplier_Email { get; set; }
        public string BookSupplier_Address { get; set; }
        public string BookSupplier_Type { get; set; }
    
        public virtual ICollection<Prospective_Book> Prospective_Book { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
