//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class The_Book_MarketEntities : DbContext
    {
        public The_Book_MarketEntities()
            : base("name=The_Book_MarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book> Books { get; set; }
        public DbSet<Book_Condition> Book_Condition { get; set; }
        public DbSet<Book_Request> Book_Request { get; set; }
        public DbSet<Book_Request_Line> Book_Request_Line { get; set; }
        public DbSet<Book_Status> Book_Status { get; set; }
        public DbSet<Book_Supplier> Book_Supplier { get; set; }
        public DbSet<Condition> Conditions { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Employee_Gender> Employee_Gender { get; set; }
        public DbSet<Employee_Title> Employee_Title { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Inventory_Level_Status> Inventory_Level_Status { get; set; }
        public DbSet<Inventory_Supplier> Inventory_Supplier { get; set; }
        public DbSet<Inventory_Supplier_Order> Inventory_Supplier_Order { get; set; }
        public DbSet<Inventory_Type> Inventory_Type { get; set; }
        public DbSet<Order_Line> Order_Line { get; set; }
        public DbSet<Order_Status> Order_Status { get; set; }
        public DbSet<Payment_Type> Payment_Type { get; set; }
        public DbSet<Prospective_Book> Prospective_Book { get; set; }
        public DbSet<Purchase> Purchases { get; set; }
        public DbSet<Purchase_Line> Purchase_Line { get; set; }
        public DbSet<Received_Supplier_Order> Received_Supplier_Order { get; set; }
        public DbSet<Return_Line> Return_Line { get; set; }
        public DbSet<Return_Sale> Return_Sale { get; set; }
        public DbSet<Return_Sale_Line> Return_Sale_Line { get; set; }
        public DbSet<Return_Supplier_Order> Return_Supplier_Order { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<Sale_Line> Sale_Line { get; set; }
        public DbSet<Stock_Turns> Stock_Turns { get; set; }
        public DbSet<TaxRate> TaxRates { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_Role> User_Role { get; set; }
        public DbSet<Write_Off_Line> Write_Off_Line { get; set; }
        public DbSet<Write_Off_Stock> Write_Off_Stock { get; set; }
    }
}
