//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Request
    {
        public Book_Request()
        {
            this.Book_Request_Line = new HashSet<Book_Request_Line>();
        }
    
        public int Book_Request_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
    
        public virtual ICollection<Book_Request_Line> Book_Request_Line { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
