//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public Condition()
        {
            this.Book_Condition = new HashSet<Book_Condition>();
        }
    
        public int Condition_ID { get; set; }
        public string Condition_Description { get; set; }
    
        public virtual ICollection<Book_Condition> Book_Condition { get; set; }
    }
}
