//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Book_Request = new HashSet<Book_Request>();
            this.Sales = new HashSet<Sale>();
            this.Sale_Line = new HashSet<Sale_Line>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Surname { get; set; }
        public string Customer_Email { get; set; }
        public Nullable<int> Customer_Contact { get; set; }
    
        public virtual ICollection<Book_Request> Book_Request { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<Sale_Line> Sale_Line { get; set; }
    }
}
