//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Type
    {
        public Inventory_Type()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int InventoryType_ID { get; set; }
        public string InventoryType_Name { get; set; }
        public string InventoryType_Description { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
