//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Supplier
    {
        public Inventory_Supplier()
        {
            this.Inventory_Supplier_Order = new HashSet<Inventory_Supplier_Order>();
            this.Received_Supplier_Order = new HashSet<Received_Supplier_Order>();
        }
    
        public int InvSupplier_ID { get; set; }
        public string InvSupp_Name { get; set; }
        public string InvSupp_Address { get; set; }
        public string InvSupp_Email { get; set; }
        public Nullable<int> InvSupp_Phone { get; set; }
    
        public virtual ICollection<Inventory_Supplier_Order> Inventory_Supplier_Order { get; set; }
        public virtual ICollection<Received_Supplier_Order> Received_Supplier_Order { get; set; }
    }
}
