//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Order_Line = new HashSet<Order_Line>();
            this.Return_Sale = new HashSet<Return_Sale>();
            this.Sale_Line = new HashSet<Sale_Line>();
            this.Write_Off_Line = new HashSet<Write_Off_Line>();
            this.Write_Off_Stock = new HashSet<Write_Off_Stock>();
        }
    
        public int Inventory_ID { get; set; }
        public Nullable<int> InventoryType_ID { get; set; }
        public string Inventory_Name { get; set; }
        public string Inventory_Description { get; set; }
        public Nullable<int> Inventory_Quantity { get; set; }
        public Nullable<int> Minimum_Quantity { get; set; }
        public Nullable<int> StockTurn_ID { get; set; }
    
        public virtual Inventory_Type Inventory_Type { get; set; }
        public virtual Stock_Turns Stock_Turns { get; set; }
        public virtual ICollection<Order_Line> Order_Line { get; set; }
        public virtual ICollection<Return_Sale> Return_Sale { get; set; }
        public virtual ICollection<Sale_Line> Sale_Line { get; set; }
        public virtual ICollection<Write_Off_Line> Write_Off_Line { get; set; }
        public virtual ICollection<Write_Off_Stock> Write_Off_Stock { get; set; }
    }
}
