//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status
    {
        public Order_Status()
        {
            this.Inventory_Supplier_Order = new HashSet<Inventory_Supplier_Order>();
            this.Order_Line = new HashSet<Order_Line>();
            this.Received_Supplier_Order = new HashSet<Received_Supplier_Order>();
        }
    
        public int SuppOrder_Status_ID { get; set; }
        public string Order_Status_Description { get; set; }
    
        public virtual ICollection<Inventory_Supplier_Order> Inventory_Supplier_Order { get; set; }
        public virtual ICollection<Order_Line> Order_Line { get; set; }
        public virtual ICollection<Received_Supplier_Order> Received_Supplier_Order { get; set; }
    }
}
