//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THe_BOok_MArket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public User_Role()
        {
            this.Users = new HashSet<User>();
        }
    
        public int UserRole_ID { get; set; }
        public string UserRole_Description { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
